### ISSUE TITLE
Error: Cannot find module 'pigpiod'

### ISSUE THREAD

**Issue by nexuspcs** [HackerHouseYT/Smartphone-Doorlock#16]
Hi all, 

As per title, when I use `node doorlock.js`, I cannot run the file/program. 
I have tried everything such as reinstalling node and pi-gpio etc.
Please, any help would be deeply appreciated 

thank you so much!

**Comment by nexuspcs** [comment]
new error.

Please any help would be extremely appreciated 
```
doorpi@doorpi:~/Smartphone-Doorlock $ node doorlock.js 
/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/Debug/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/Release/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/out/Debug/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/Debug/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/out/Release/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/Release/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/default/pigpio.node
 → /home/doorpi/Smartphone-Doorlock/node_modules/pigpio/compiled/16.15.1/linux/arm/pigpio.node
    at bindings (/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:5:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/doorpi/Smartphone-Doorlock/doorlock.js:47:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14) {
  tries: [
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/Debug/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/Release/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/out/Debug/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/Debug/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/out/Release/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/Release/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/build/default/pigpio.node',
    '/home/doorpi/Smartphone-Doorlock/node_modules/pigpio/compiled/16.15.1/linux/arm/pigpio.node'
  ]
}

```
