### ISSUE TITLE
Issue with the Code

### ISSUE THREAD

**Issue by arnab08121987** [HackerHouseYT/Smartphone-Doorlock#5]
Hello ,

I am getting the below error :

pi@raspberrypi:~/Smartphone-Doorlock $ sudo node doorlock.js
/home/pi/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:137
  pigpio.gpioSetISRFunc(this.gpio, +edge, +timeout, handler);
         

Error: pigpio error -123 in gpioSetISRFunc
    at Error (native)
    at Gpio.enableInterrupt (/home/pi/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:137:10)
    at new Gpio (/home/pi/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:40:10)
    at Object. (/home/pi/Smartphone-Doorlock/doorlock.js:49:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

I am using the RASPBERRY PI 3 with RASPBIAN Installed . Placed the Signal Wire in 14 Slot as mentioned in Code. But I am getting this error. 

Please assist me.

**Comment by skylerm521** [comment]
@arnab08121987 
I have the exact same issue on the same OS.  Did you ever figure out what the problem was?

**Comment by MicahMaze** [comment]
Same issue. Any help?

**Comment by andrewpatterson3001** [comment]
I'm also seeing this error, but I think it's a pigpio issue, not a Smartphone-Doorlock one. Anyone here know what to do?

**Comment by rashmin1213** [comment]
I am having the same issue, did anyone find a solution to this?
