### ISSUE TITLE
Can't run it, need help! 

### ISSUE THREAD

**Issue by zdqxxx124** [HackerHouseYT/Smartphone-Doorlock#8]
I tried step by step, and getting error following:

`pi@raspi:~/Smartphone-Doorlock $ sudo node doorlock.js
fs.js:91
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "options" argument must be one of type string or Object. Received type number
    at getOptions (fs.js:91:11)
    at fs.readFileSync (fs.js:570:13)
    at Array.map (<anonymous>)
    at exports.SslClient.connect (/home/pi/Smartphone-Doorlock/node_modules/blynk-library/blynk-node.js:169:42)
    at doConnect (/home/pi/Smartphone-Doorlock/node_modules/blynk-library/blynk.js:546:15)
    at Blynk.connect (/home/pi/Smartphone-Doorlock/node_modules/blynk-library/blynk.js:559:5)
    at new Blynk (/home/pi/Smartphone-Doorlock/node_modules/blynk-library/blynk.js:385:10)
    at Object.<anonymous> (/home/pi/Smartphone-Doorlock/doorlock.js:58:13)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
`

**Comment by lisaong** [comment]
This is an issue with the Blynk library: https://github.com/vshymanskyy/blynk-library-js/issues/26, try updating package.json to use the latest library.

```
diff --git a/package.json b/package.json
index 5f1367e..1063c50 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
   "author": "",
   "license": "ISC",
   "dependencies": {
-    "blynk-library": "0.0.41",
+    "blynk-library": "0.5.1",
     "onoff": "^1.1.1",
     "pigpio": "^0.4.0"
   }
 ```

**Comment by SIDECHAIN3D** [comment]
Encountered same issue.  A simple "sudo npm rebuild" did the trick.

**Comment by Scout-lander** [comment]
hi im also having running issues  


  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/Debug/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/Release/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/out/Debug/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/Debug/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/out/Release/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/Release/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/default/pigpio.node
 → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/compiled/10.11.0/linux/arm/pigpio.node
    at bindings (/home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:5:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/cam/Smartphone-Doorlock/doorlock.js:47:12)

**Comment by Mr-Black-Dahlia** [comment]
> hi im also having running issues
> 
> throw err
> ^
> 
> Error: Could not locate the bindings file. Tried:
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/Debug/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/Release/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/out/Debug/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/Debug/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/out/Release/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/Release/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/build/default/pigpio.node
> → /home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/compiled/10.11.0/linux/arm/pigpio.node
> at bindings (/home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/node_modules/bindings/bindings.js:88:9)
> at Object. (/home/pi/cam/Smartphone-Doorlock/node_modules/pigpio/pigpio.js:5:31)
> at Module._compile (internal/modules/cjs/loader.js:689:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
> at Module.load (internal/modules/cjs/loader.js:599:32)
> at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
> at Function.Module._load (internal/modules/cjs/loader.js:530:3)
> at Module.require (internal/modules/cjs/loader.js:637:17)
> at require (internal/modules/cjs/helpers.js:20:18)
> at Object. (/home/pi/cam/Smartphone-Doorlock/doorlock.js:47:12)

Don't follow the suggested guide to install node or npm. :) Start over and just use apt-get. Worked for me!

**Comment by jgonzales489** [comment]
How did you bbn I stall node then if I type npm-get it throws locked  issues
